
# Project information
site_name: Archives de la construction moderne (Acm)
site_url: https://gr-acm.github.io

# Repository
repo_url: https://github.com/GR-ACM/gr-acm.github.io
repo_name: GR-ACM/gr-acm.github.io

# Copyright
copyright: Copyright &copy; 2025 ENAC IA GR-ACM

# Configuration
theme:
  name: material
  language: fr
  font:
    text: Source Sans 3
    code: Source Code Pro

  logo: assets/epfl.svg
  favicon: assets/epfl.svg

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - i18n

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
      primary: black
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
      primary: indigo
      accent: red

plugins:
  - search
  - privacy
  - i18n:
      languages:
        - locale: fr
          name: Français
          build: true
          default: true
          nav:
            - Accueil: index.md
            - Wiki: wiki/under-construction.md
            - Ressources:
              - Git:
                - Exclusion de fichiers dans un dépôt MkDocs: resources/git/gitignore.md
              - Scripts:
                - Intégration des métadonnées pour Archivematica et AtoM: resources/scripts/AtoM-METS-merger.md
                - Injection des métadonnées dans AtoM: resources/scripts/AtoM-record-updater.md
            - À propos:
                - Présentation technique: meta/overview.md
                - Installation initiale: meta/installation.md
                - Personnalisation visuelle: meta/theme.md
                - Structuration du contenu: meta/structure.md
                - Configuration avancée: meta/advanced.md
                - Publication: meta/publish.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: index.md
            - Wiki: wiki/under-construction.md
            - Resources:
              - Git:
                - .gitignore file: resources/git/gitignore.md
              - Scripts:
                - Metadata Integration Package for Archivematica and AtoM: resources/scripts/AtoM-METS-merger.md
                - Metadata injection in AtoM: resources/scripts/AtoM-record-updater.md
            - About:
                - Technical overview: meta/overview.md
                - Installation: meta/installation.md
                - Visual customization: meta/theme.md
                - Structuring content: meta/structure.md
                - Advanced configuration: meta/advanced.md
                - Publishing: meta/publish.md

extra:
  social:
    - icon: material/web
      link: https://www.epfl.ch/schools/enac/acm/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists